apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- components/java-quarkus-test/base
- components/java-quarkus/base
- components/nodeapp/base
- components/nodejs/base
- components/python/base
- components/pythont/base
kind: Kustomization
