apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-test
    app.kubernetes.io/part-of: test-application
  name: java-quarkus-test
  namespace: karthik-jk
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: java-quarkus-test
    weight: 100
status: {}
